plugins {
	id 'fabric-loom' version '1.17.20'
	id 'java'
}
version = project.mod_version
group = project.maven_group
base {
	archivesName = project.archives_base_name
}
repositories {
	maven { url = 'https://maven.fabricmc.net/' }
	mavenCentral()
}
loom {
	accessWidenerPath = file("src/main/resources/novaclient.accesswidener")
	mods {
		"novaclient" {
			sourceSet sourceSets.main
		}
	}
}
dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	testImplementation platform('org.junit:junit-bom:5.10.2')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test {
	useJUnitPlatform()
	testLogging {
		events 'passed', 'failed', 'skipped'
		exceptionFormat = 'full'
		showStandardStreams = false
	}
}
processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}
tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.encoding = 'UTF-8'
}
java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
jar {
	from('LICENSE') {
		rename { "${it}_${project.archives_base_name}" }
	}
}
